allowBuilds:
  '@claude-flow/cli': true
  '@google/genai': true
  agentdb: true
  agentic-flow: true
  argon2: true
  better-sqlite3: true
  core-js: true
  esbuild: true
  hnswlib-node: true
  protobufjs: true
  sharp: true
  tldjs: true
